import { FastifyRequest, FastifyReply } from 'fastify';
import { logger } from '../config/logger';
import { ApiResponseHelper } from '../utils';
import { verifyToken, isTokenExpired, extractUserId, extractTenantId, validateProductToken } from '@shared/utils/jwt';

/**
 * Validate JWT token and extract account context
 *
 * Functionality:
 * - Expects Bearer token with JWT format
 * - Verifies JWT signature using JWT_SECRET from environment
 * - Validates token is not expired
 * - Extracts account_id from JWT payload
 * - Sets context headers for downstream handlers (x-account-id, x-user-id, etc.)
 * - Compatible with tokens generated by auth-service
 *
 * Token Requirements:
 * - Must be product-scoped token (type: 'product')
 * - Must have resource_id (tenant ID)
 * - Must have account_id
 * - Must have sub (user ID)
 * - Must have email
 * - Must not be expired
 */
export async function authMiddleware(request: FastifyRequest, reply: FastifyReply) {
  const authHeader = request.headers.authorization;

  if (!authHeader) {
    logger.warn({ requestId: request.id }, 'Missing authorization header');
    ApiResponseHelper.unauthorized(reply, 'Missing authorization header');
    return;
  }

  // Handle both "Bearer token" and plain "token" formats
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : authHeader;

  if (!token) {
    logger.warn({ requestId: request.id }, 'Missing bearer token');
    ApiResponseHelper.unauthorized(reply, 'Missing bearer token');
    return;
  }

  // Verify JWT token with signature validation
  const payload = verifyToken(token);

  if (!payload) {
    logger.warn({ requestId: request.id }, 'Invalid JWT signature or format');
    ApiResponseHelper.unauthorized(reply, 'Invalid or malformed token');
    return;
  }

  // Check token expiration
  if (isTokenExpired(payload)) {
    logger.warn({ requestId: request.id, userId: payload.sub }, 'Token has expired');
    ApiResponseHelper.tokenExpired(reply, 'Token has expired');
    return;
  }

  // Validate product-scoped token (required for resource access)
  const tokenValidation = validateProductToken(payload);
  if (!tokenValidation.valid) {
    logger.warn({ requestId: request.id, userId: payload.sub }, tokenValidation.error);
    ApiResponseHelper.unauthorized(reply, tokenValidation.error);
    return;
  }

  const tenantId = extractTenantId(payload);
  const userId = extractUserId(payload);
  const accountId = payload.account_id;

  if (!tenantId || !userId) {
    logger.error({ requestId: request.id, payload }, 'Token missing required claims (userId or tenantId)');
    ApiResponseHelper.unauthorized(reply, 'Token missing required claims');
    return;
  }

  if (!accountId) {
    logger.error({ requestId: request.id, payload }, 'Token missing account_id claim');
    ApiResponseHelper.unauthorized(reply, 'Token missing account_id');
    return;
  }

  // Set context headers for downstream handlers
  request.headers['x-tenant-id'] = tenantId;
  request.headers['x-user-id'] = userId;
  request.headers['x-user-email'] = payload.email || '';
  request.headers['x-user-role'] = payload.role || 'member';
  request.headers['x-account-id'] = accountId;
  request.headers['x-account-type'] = payload.account_type || 'INDIVIDUAL';

  // Attach user info to request for downstream use
  (request as any).user = {
    id: userId,
    email: payload.email,
    account_ids: [accountId],
    account_type: payload.account_type || 'INDIVIDUAL',
  };

  logger.debug(
    {
      requestId: request.id,
      tenantId,
      userId,
      userEmail: payload.email,
      accountId,
    },
    'JWT token validated - account context set'
  );
}

/**
 * Validate base JWT token for auth endpoints
 *
 * Functionality:
 * - Validates base tokens from auth-service
 * - Does NOT require product scope
 * - Extracts user info from token payload
 * - Sets context for downstream handlers
 * - Used for /auth/profile, /auth/organizations endpoints
 */
export async function validateBaseToken(request: FastifyRequest, reply: FastifyReply) {
  const authHeader = request.headers.authorization;

  if (!authHeader) {
    logger.warn({ requestId: request.id }, 'Missing authorization header');
    return ApiResponseHelper.unauthorized(reply, 'Missing authorization header');
  }

  // Handle both "Bearer token" and plain "token" formats
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : authHeader;

  if (!token) {
    logger.warn({ requestId: request.id }, 'Missing bearer token');
    return ApiResponseHelper.unauthorized(reply, 'Missing bearer token');
  }

  // Verify JWT token
  const payload = verifyToken(token);

  if (!payload) {
    logger.warn({ requestId: request.id }, 'Invalid JWT signature or format');
    return ApiResponseHelper.unauthorized(reply, 'Invalid or malformed token');
  }

  // Check token expiration
  if (isTokenExpired(payload)) {
    logger.warn({ requestId: request.id, userId: payload.userId || payload.sub }, 'Token has expired');
    return ApiResponseHelper.tokenExpired(reply, 'Token has expired');
  }

  const userId = payload.userId || payload.sub;
  if (!userId) {
    logger.error({ requestId: request.id, payload }, 'Token missing userId');
    return ApiResponseHelper.unauthorized(reply, 'Token missing required claims');
  }

  // Set context for downstream handlers
  request.headers['x-user-id'] = userId;
  request.headers['x-user-email'] = payload.email || '';

  // Attach user info to request
  (request as any).user = {
    id: userId,
    email: payload.email,
  };

  logger.debug(
    {
      requestId: request.id,
      userId,
      userEmail: payload.email,
    },
    'Base token validated'
  );
}
