import { FastifyRequest, FastifyReply } from 'fastify';
import { logger } from '../config/logger';
import { tenantRepository } from '../repositories/tenant.repository';
import { ApiResponseHelper } from '../utils';
import { verifyToken, isTokenExpired, extractUserId, extractTenantId, validateProductToken } from '@shared/utils/jwt';

/**
 * Validate JWT token and extract tenant context from resource_id
 *
 * Functionality:
 * - Expects Bearer token with JWT format
 * - Verifies JWT signature using JWT_SECRET from environment
 * - Validates token is not expired
 * - Extracts resource_id (tenant ID) from JWT payload
 * - Validates tenant exists in database and is active
 * - Sets context headers for downstream handlers (x-tenant-id, x-user-id, etc.)
 * - Compatible with tokens generated by auth-service
 *
 * Token Requirements:
 * - Must be product-scoped token (type: 'product')
 * - Must have resource_id (tenant ID)
 * - Must have account_id
 * - Must have sub (user ID)
 * - Must have email
 * - Must not be expired
 */
export async function authMiddleware(request: FastifyRequest, reply: FastifyReply) {
  const authHeader = request.headers.authorization;

  if (!authHeader) {
    logger.warn({ requestId: request.id }, 'Missing authorization header');
    ApiResponseHelper.unauthorized(reply, 'Missing authorization header');
    return;
  }

  // Handle both "Bearer token" and plain "token" formats
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : authHeader;

  if (!token) {
    logger.warn({ requestId: request.id }, 'Missing bearer token');
    ApiResponseHelper.unauthorized(reply, 'Missing bearer token');
    return;
  }

  // Verify JWT token with signature validation
  const payload = verifyToken(token);

  if (!payload) {
    logger.warn({ requestId: request.id }, 'Invalid JWT signature or format');
    ApiResponseHelper.unauthorized(reply, 'Invalid or malformed token');
    return;
  }

  // Check token expiration
  if (isTokenExpired(payload)) {
    logger.warn({ requestId: request.id, userId: payload.sub }, 'Token has expired');
    ApiResponseHelper.tokenExpired(reply, 'Token has expired');
    return;
  }

  // Validate product-scoped token (required for resource access)
  const tokenValidation = validateProductToken(payload);
  if (!tokenValidation.valid) {
    logger.warn({ requestId: request.id, userId: payload.sub }, tokenValidation.error);
    ApiResponseHelper.unauthorized(reply, tokenValidation.error);
    return;
  }

  const tenantId = extractTenantId(payload);
  const userId = extractUserId(payload);

  if (!tenantId || !userId) {
    logger.error({ requestId: request.id, payload }, 'Token missing required claims (userId or tenantId)');
    ApiResponseHelper.unauthorized(reply, 'Token missing required claims');
    return;
  }

  // Validate tenant exists in database
  try {
    const tenant = await tenantRepository.findById(tenantId);

    if (!tenant) {
      logger.warn({ requestId: request.id, tenantId }, 'Tenant not found for provided resource_id');
      ApiResponseHelper.notFound(reply, 'Tenant not found');
      return;
    }

    // Validate tenant is active
    if (tenant.status !== 'ACTIVE') {
      logger.warn({ requestId: request.id, tenantId }, 'Tenant is not active');
      ApiResponseHelper.forbidden(reply, 'Tenant is not active');
      return;
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    logger.error({ requestId: request.id, tenantId, error: errorMessage }, 'Failed to validate tenant');
    ApiResponseHelper.badRequest(reply, 'Failed to validate tenant');
    return;
  }

  // Set context headers for downstream handlers
  request.headers['x-tenant-id'] = tenantId;
  request.headers['x-user-id'] = userId;
  request.headers['x-user-email'] = payload.email || '';
  request.headers['x-user-role'] = payload.role || 'member';
  request.headers['x-account-id'] = payload.account_id || '';
  request.headers['x-account-type'] = payload.account_type || 'INDIVIDUAL';

  logger.debug(
    {
      requestId: request.id,
      tenantId,
      userId,
      userEmail: payload.email,
      accountId: payload.account_id,
    },
    'JWT token validated - tenant context set'
  );
}
