import { FastifyRequest, FastifyReply } from 'fastify';
import { logger } from '../config/logger';
import { ApiResponseHelper } from '../utils';
import { verifyToken, isTokenExpired, extractUserId, extractTenantId, validateProductToken } from '@shared/utils/jwt';
import { apiKeyMiddleware } from './api-key.middleware';

/**
 * Validate JWT token and extract account context
 *
 * Functionality:
 * - Expects Bearer token with JWT format
 * - Verifies JWT signature using JWT_SECRET from environment
 * - Validates token is not expired
 * - Extracts account_id from JWT payload
 * - Sets context headers for downstream handlers (x-account-id, x-user-id, etc.)
 * - Compatible with tokens generated by auth-service
 *
 * Token Requirements:
 * - Must be product-scoped token (type: 'product')
 * - Must have resource_id (tenant ID)
 * - Must have account_id
 * - Must have sub (user ID)
 * - Must have email
 * - Must not be expired
 */
export async function authMiddleware(request: FastifyRequest, reply: FastifyReply) {
  const authHeader = request.headers.authorization;

  if (!authHeader) {
    logger.warn({ requestId: request.id }, 'Missing authorization header');
    ApiResponseHelper.unauthorized(reply, 'Missing authorization header');
    return;
  }

  // Handle both "Bearer token" and plain "token" formats
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : authHeader;

  if (!token) {
    logger.warn({ requestId: request.id }, 'Missing bearer token');
    ApiResponseHelper.unauthorized(reply, 'Missing bearer token');
    return;
  }

  // Verify JWT token with signature validation
  const payload = verifyToken(token);

  if (!payload) {
    logger.warn({ requestId: request.id }, 'Invalid JWT signature or format');
    ApiResponseHelper.unauthorized(reply, 'Invalid or malformed token');
    return;
  }

  // Check token expiration
  if (isTokenExpired(payload)) {
    logger.warn({ requestId: request.id, userId: payload.sub }, 'Token has expired');
    ApiResponseHelper.tokenExpired(reply, 'Token has expired');
    return;
  }

  // Validate product-scoped token (required for resource access)
  const tokenValidation = validateProductToken(payload);
  if (!tokenValidation.valid) {
    logger.warn({ requestId: request.id, userId: payload.sub }, tokenValidation.error);
    ApiResponseHelper.unauthorized(reply, tokenValidation.error);
    return;
  }

  const tenantId = extractTenantId(payload);
  const userId = extractUserId(payload);
  const accountId = payload.account_id;

  if (!tenantId || !userId) {
    logger.error({ requestId: request.id, payload }, 'Token missing required claims (userId or tenantId)');
    ApiResponseHelper.unauthorized(reply, 'Token missing required claims');
    return;
  }

  if (!accountId) {
    logger.error({ requestId: request.id, payload }, 'Token missing account_id claim');
    ApiResponseHelper.unauthorized(reply, 'Token missing account_id');
    return;
  }

  // Set context headers for downstream handlers
  request.headers['x-tenant-id'] = tenantId;
  request.headers['x-user-id'] = userId;
  request.headers['x-user-email'] = payload.email || '';
  request.headers['x-user-role'] = payload.role || 'member';
  request.headers['x-account-id'] = accountId;
  request.headers['x-account-type'] = payload.account_type || 'INDIVIDUAL';

  // Attach user info to request for downstream use
  (request as any).user = {
    id: userId,
    email: payload.email,
    account_ids: [accountId],
    account_type: payload.account_type || 'INDIVIDUAL',
  };

  logger.debug(
    {
      requestId: request.id,
      tenantId,
      userId,
      userEmail: payload.email,
      accountId,
    },
    'JWT token validated - account context set'
  );
}

/**
 * Validate base JWT token for auth endpoints
 *
 * Functionality:
 * - Validates base tokens from auth-service
 * - Does NOT require product scope
 * - Extracts user info from token payload
 * - Sets context for downstream handlers
 * - Used for /auth/profile, /auth/organizations endpoints
 */
export async function validateBaseToken(request: FastifyRequest, reply: FastifyReply) {
  const authHeader = request.headers.authorization;

  if (!authHeader) {
    logger.warn({ requestId: request.id }, 'Missing authorization header');
    return ApiResponseHelper.unauthorized(reply, 'Missing authorization header');
  }

  // Handle both "Bearer token" and plain "token" formats
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : authHeader;

  if (!token) {
    logger.warn({ requestId: request.id }, 'Missing bearer token');
    return ApiResponseHelper.unauthorized(reply, 'Missing bearer token');
  }

  // Verify JWT token
  const payload = verifyToken(token);

  if (!payload) {
    logger.warn({ requestId: request.id }, 'Invalid JWT signature or format');
    return ApiResponseHelper.unauthorized(reply, 'Invalid or malformed token');
  }

  // Check token expiration
  if (isTokenExpired(payload)) {
    logger.warn({ requestId: request.id, userId: payload.userId || payload.sub }, 'Token has expired');
    return ApiResponseHelper.tokenExpired(reply, 'Token has expired');
  }

  const userId = payload.userId || payload.sub;
  if (!userId) {
    logger.error({ requestId: request.id, payload }, 'Token missing userId');
    return ApiResponseHelper.unauthorized(reply, 'Token missing required claims');
  }

  // Set context for downstream handlers
  request.headers['x-user-id'] = userId;
  request.headers['x-user-email'] = payload.email || '';
  request.headers['x-user-role'] = payload.role || '';

  // Attach user info to request
  (request as any).user = {
    id: userId,
    email: payload.email,
    role: payload.role,
    account_id: payload.account_id,
    account_type: payload.account_type,
  };

  logger.debug(
    {
      requestId: request.id,
      userId,
      userEmail: payload.email,
      role: payload.role,
    },
    'Base token validated'
  );
}

/**
 * Restrict access to platform-staff admin roles (SUPER_ADMIN, OPS_MANAGER -
 * see platform-frontend's `ControlRole` / `PLATFORM_WIDE_ROLES`). This is a
 * staff console, not a per-account role like an account owner.
 *
 * Must run after `validateBaseToken` (or `authMiddleware`), which populates
 * `request.user.role`. This is the notify-service-side half of the two-layer
 * check - the gateway already restricts these routes by role, this is
 * defense in depth in case the service is ever reached directly.
 */
const PLATFORM_ADMIN_ROLES = ['SUPER_ADMIN', 'OPS_MANAGER'];

export async function requirePlatformAdmin(request: FastifyRequest, reply: FastifyReply) {
  const role = (request as any).user?.role;

  if (!role || !PLATFORM_ADMIN_ROLES.includes(role)) {
    logger.warn(
      { requestId: request.id, userId: (request as any).user?.id, role, path: request.url },
      'Platform admin access denied: insufficient role'
    );
    return ApiResponseHelper.forbidden(reply, 'Platform administrator access required');
  }
}

/**
 * Stricter than `requirePlatformAdmin`: only SUPER_ADMIN, not OPS_MANAGER.
 * Use on endpoints that touch shared infrastructure directly (e.g. the mail
 * server's Postfix config over SSH), where a broader "platform admin" grant
 * is more access than the operation warrants.
 */
export async function requireSuperAdmin(request: FastifyRequest, reply: FastifyReply) {
  const role = (request as any).user?.role;

  if (role !== 'SUPER_ADMIN') {
    logger.warn(
      { requestId: request.id, userId: (request as any).user?.id, role, path: request.url },
      'Super admin access denied: insufficient role'
    );
    return ApiResponseHelper.forbidden(reply, 'Super administrator access required');
  }
}

/**
 * Flexible auth middleware that accepts either a JWT token or an API key.
 * Detects the token type by the `sk_` prefix and delegates accordingly.
 * Both paths set `x-account-id` so downstream handlers are auth-agnostic.
 */
export async function flexAuthMiddleware(request: FastifyRequest, reply: FastifyReply) {
  const authHeader = request.headers.authorization;

  if (!authHeader) {
    return ApiResponseHelper.unauthorized(reply, 'Missing authorization header');
  }

  const [scheme, token] = authHeader.split(' ');

  if (scheme !== 'Bearer' || !token) {
    return ApiResponseHelper.unauthorized(reply, 'Invalid authorization scheme');
  }

  if (token.startsWith('sk_')) {
    return apiKeyMiddleware(request, reply);
  }

  return validateBaseToken(request, reply);
}
