export const NOTIFICATION_CHANNELS = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  IN_APP: 'IN_APP',
  PUSH: 'PUSH',
};

// Notification Templates
export const NOTIFICATION_TEMPLATES = {
  AUTH_VERIFY_EMAIL: 'AUTH_VERIFY_EMAIL',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_LOGIN_OTP: 'AUTH_LOGIN_OTP',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_NEW_DEVICE_LOGIN: 'AUTH_NEW_DEVICE_LOGIN',
  TRANSACTIONAL_INVOICE: 'TRANSACTIONAL_INVOICE',
  TRANSACTIONAL_RECEIPT: 'TRANSACTIONAL_RECEIPT',
  MARKETING_NEWSLETTER: 'MARKETING_NEWSLETTER',
  NOTIFICATION_ALERT: 'NOTIFICATION_ALERT',
};
