export enum AlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum AlertType {
  CIRCUIT_BREAKER_OPEN = 'CIRCUIT_BREAKER_OPEN',
  CIRCUIT_BREAKER_RECOVERED = 'CIRCUIT_BREAKER_RECOVERED',
  DLQ_THRESHOLD_EXCEEDED = 'DLQ_THRESHOLD_EXCEEDED',
  RATE_LIMIT_ABUSE = 'RATE_LIMIT_ABUSE',
  PROVIDER_FAILURE = 'PROVIDER_FAILURE',
  EMAIL_PROVIDER_UNHEALTHY = 'EMAIL_PROVIDER_UNHEALTHY',
  HIGH_ERROR_RATE = 'HIGH_ERROR_RATE',
  USAGE_LIMIT_CRITICAL = 'USAGE_LIMIT_CRITICAL',
}
