/**
 * JWT Utilities - Shared with Auth Service
 * Token generation and verification for unified authentication
 */

import jwt from 'jsonwebtoken';

// Get JWT secret from environment
const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key-change-in-production';

/**
 * Verify and decode JWT token
 * Compatible with tokens generated by auth-service
 * @throws Error if JWT_SECRET is not properly configured
 */
export const verifyToken = (token: string) => {
  try {
    return jwt.verify(token, JWT_SECRET) as {
      sub?: string;
      userId?: string;
      email: string;
      account_ids?: string[];
      account_id?: string;
      account_type?: 'INDIVIDUAL' | 'ORGANIZATION';
      product?: string;
      resource_id?: string;
      role?: string;
      type?: 'base' | 'product';
      iat?: number;
      exp?: number;
    };
  } catch {
    // Return null on verification failure - caller handles logging
    return null;
  }
};

/**
 * Validate token is not expired
 */
export const isTokenExpired = (payload: any): boolean => {
  if (!payload.exp) return false;
  const now = Math.floor(Date.now() / 1000);
  return payload.exp < now;
};

/**
 * Extract user ID from token (supports both 'sub' and 'userId' fields)
 */
export const extractUserId = (payload: any): string | null => {
  return payload.sub || payload.userId || null;
};

/**
 * Extract tenant ID (resource_id) from token
 */
export const extractTenantId = (payload: any): string | null => {
  return payload.resource_id || null;
};

/**
 * Extract account ID from token
 */
export const extractAccountId = (payload: any): string | null => {
  return payload.account_id || null;
};

/**
 * Validate token has required product-scoped claims
 * Returns validation result with error message if invalid
 */
export const validateProductToken = (payload: any): { valid: boolean; error?: string } => {
  // Must be a product-scoped token
  if (payload.type !== 'product') {
    return {
      valid: false,
      error: 'Token must be product-scoped. Use /auth/switch-product to get product token.',
    };
  }

  // Must have resource_id (tenant ID)
  if (!payload.resource_id) {
    return {
      valid: false,
      error: 'Token missing required resource_id claim',
    };
  }

  // Must have account_id
  if (!payload.account_id) {
    return {
      valid: false,
      error: 'Token missing required account_id claim',
    };
  }

  // Must have product
  if (!payload.product) {
    return {
      valid: false,
      error: 'Token missing required product claim',
    };
  }

  return { valid: true };
};

/**
 * Validate token has required base claims (for accessing multiple accounts)
 */
export const validateBaseToken = (payload: any): { valid: boolean; error?: string } => {
  if (payload.type !== 'base') {
    return {
      valid: false,
      error: 'Token must be base token type',
    };
  }

  if (!payload.account_ids || !Array.isArray(payload.account_ids)) {
    return {
      valid: false,
      error: 'Token missing required account_ids claim',
    };
  }

  return { valid: true };
};
